# Generated by Django 3.2.6 on 2021-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField()),
                ('post_text', models.TextField(max_length=1000)),
                ('post_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
